kind: Deployment
apiVersion: apps/v1
metadata:
  name: guestbook
  namespace: guestbook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guestbook
      tier: frontend
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: guestbook
        tier: frontend
    spec:
      containers:
        - name: php-redis
          image: >-
            gcr.io/google-samples/gb-frontend@sha256:e5233a1e2a6dc9c4ae1d1b754e3a3f62ecdc1da81b31422aff4e7390a0c6e534
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: GET_HOSTS_FROM
              value: env
            - name: REDIS_LEADER_SERVICE_HOST
              value: redis-leader.guestbook.svc.clusterset.local
            - name: REDIS_FOLLOWER_SERVICE_HOST
              value: redis-follower.guestbook.svc.clusterset.local
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
